### ISSUE TITLE
Not working in gnome-shell 3.32

### ISSUE THREAD

**Issue by kiendang** [bertoldia/gnome-shell-trash-extension#21]
Error message from gnome-shell:
```
Extension "gnome-shell-trash-extension" had error: TypeError: this._construct is not a function
```

Thanks for writing the extension btw.
